name: Build and Push - PHP 83

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'
  push:
    branches:
      - master
    paths:
      - php83/**

env:
  REGISTRY: docker.io
  IMAGE_NAME: labordigital/docker-base-images-v2
  BASE_TAG: php83

jobs:
  buildAndPush:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Base Image
      - name: Build and push base image
        uses: docker/build-push-action@v5
        with:
          context: ./${{ env.BASE_TAG }}/${{ env.BASE_TAG }}/.
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.BASE_TAG }}
          platforms: linux/amd64,linux/arm64
          file: ./${{ env.BASE_TAG }}/${{ env.BASE_TAG }}/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Dev Image
      - name: Checkout ssl certs
        uses: actions/checkout@v4
        with:
          repository: labor-digital/ssl-certs
          path: ./${{ env.BASE_TAG }}/${{ env.BASE_TAG }}-dev/ssl
      - name: Build and push dev image
        uses: docker/build-push-action@v5
        with:
          context: ./${{ env.BASE_TAG }}/${{ env.BASE_TAG }}-dev/.
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.BASE_TAG }}-dev
          platforms: linux/amd64,linux/arm64
          file: ./${{ env.BASE_TAG }}/${{ env.BASE_TAG }}-dev/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
