name: Build and Push - php83

on:
  workflow_dispatch:
#  schedule:
#    - cron: '0 8 * * *'
#  push:
#    branches:
#      - master
#    paths:
#      - php83-v2/**

env:
  REGISTRY: docker.io
  IMAGE_NAME: labordigital/docker-base-images-v2
  SOURCE_TAG: 8.3-apache
  BASE_TAG: php83
  BASE_TAG_TEMP: php83-v2
  EXT: -dev

jobs:
  buildAndPush:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 14

      - name: Login to DockerHub Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=auto
          tags: |
            type=raw,value=${{ env.BASE_TAG_TEMP }}

      - name: Build and push base image
        uses: docker/build-push-action@v5
        with:
          context: ./${{ env.BASE_TAG_TEMP }}/${{ env.BASE_TAG }}/.
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          file: ./${{ env.BASE_TAG_TEMP }}/${{ env.BASE_TAG }}/Dockerfile
          build-args: |
            SOURCE_TAG=${{ env.SOURCE_TAG }}
            BASE_TAG=${{ env.BASE_TAG_TEMP }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
  buildAndPushDev:
    needs: buildAndPush
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 14

      - name: Login to DockerHub Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=auto
          tags: |
            type=raw,value=${{ env.BASE_TAG_TEMP }}${{ env.EXT }}

      - name: Build and push base image
        uses: docker/build-push-action@v5
        with:
          context: ./${{ env.BASE_TAG_TEMP }}/${{ env.BASE_TAG }}${{ env.EXT }}/.
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          file: ./${{ env.BASE_TAG_TEMP }}/${{ env.BASE_TAG }}${{ env.EXT }}/Dockerfile
          build-args: |
            BASE_TAG=${{ env.BASE_TAG_TEMP }}
          cache-from: type=gha
          cache-to: type=gha,mode=max